name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - run: |
        pip install indexed_gzip
        head -c 10G </dev/urandom >temp_10GB_file
        python tst-index.py
