name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - run: |
        pip install indexed_gzip
        head -c 1G </dev/urandom >temp_1GB_file
        gzip -k temp_1GB_file

        head -c 10G </dev/urandom >temp_10GB_file
        gzip -k temp_10GB_file
    - run: python tst-index.py
