name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_1g:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.7
    - run: |
        pip install indexed-gzip
        head -c 1G </dev/urandom >temp_file
        gzip -k temp_file
    - run: python tst-index.py

  test_10g:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.7
    - run: |
        pip install indexed-gzip
        head -c 10G </dev/urandom >temp_file
        gzip -k temp_file
    - run: python tst-index.py
