name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - run: git clone https://github.com/codalab/codalab-worksheets.git
    - run: ls
    - run: pwd
    - run: cp tst-index.py codalab-worksheets/
    - run: cd codalab-worksheets
    - run: head -c 10G </dev/urandom >temp_10GB_file
    - run: python tst-index.py
